import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the Golden Gate flight experience shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();

  assert.match(html, /<title>Golden Gate Flight/);
  assert.match(html, /Golden Gate/);
  assert.match(html, /Return to bridge/);
  assert.match(html, /Deployment information/);
  assert.match(html, /Source revision/);
  assert.match(html, /Environment controls/);
  assert.doesNotMatch(html, /Begin flight|Resume flight|capture the mouse/i);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape/i);
});

test("includes free-flight and environmental controls", async () => {
  const [experience, scene, packageJson] = await Promise.all([
    readFile(new URL("app/components/BridgeExperience.tsx", root), "utf8"),
    readFile(new URL("app/components/GoldenGateScene.tsx", root), "utf8"),
    readFile(new URL("package.json", root), "utf8"),
  ]);

  assert.match(experience, /timeOfDay/);
  assert.match(experience, /fogLevel/);
  assert.match(experience, /data-testid="sunlight-control"/);
  assert.match(experience, /data-testid="fog-control"/);
  assert.match(scene, /pointerdown|pointermove/);
  assert.match(scene, /DRAG_THRESHOLD_PX/);
  assert.match(scene, /rotation\.reorder\("YXZ"\)/);
  assert.doesNotMatch(scene, /rotation\.order\s*=/);
  assert.doesNotMatch(scene, /pointerLockElement|requestPointerLock|setPointerCapture/);
  assert.doesNotMatch(experience, /started|pointerLockFailed|requestFlightLock/);
  assert.match(experience, /Return to bridge/);
  assert.match(scene, /KeyW|KeyA|KeyS|KeyD/);
  assert.match(scene, /GoldenGateBridge/);
  assert.match(scene, /Water/);
  assert.match(scene, /Stars/);
  assert.match(packageJson, /"three"/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);

  await assert.rejects(access(new URL("app/_sites-preview", root)));
});

test("lets Vinext own Cloudflare compatibility flags", async () => {
  const [viteConfig, wranglerConfig] = await Promise.all([
    readFile(new URL("vite.config.ts", root), "utf8"),
    readFile(new URL("wrangler.jsonc", root), "utf8"),
  ]);

  assert.doesNotMatch(
    viteConfig,
    /compatibility_flags/,
    "Declaring nodejs_compat here duplicates the flag generated by vinext deploy",
  );
  assert.equal(
    wranglerConfig.match(/nodejs_compat/g)?.length,
    1,
    "The deploy configuration must declare nodejs_compat exactly once",
  );
});

test("stamps deployments with their Git source revision", async () => {
  const [experience, viteConfig] = await Promise.all([
    readFile(new URL("app/components/BridgeExperience.tsx", root), "utf8"),
    readFile(new URL("vite.config.ts", root), "utf8"),
  ]);

  assert.match(viteConfig, /WORKERS_CI_COMMIT_SHA/);
  assert.match(viteConfig, /WORKERS_CI_BRANCH/);
  assert.match(experience, /REPOSITORY_URL.*github\.com\/chunhualiao\/golden-gate-flight/);
  assert.match(experience, /REPOSITORY_URL}\/commit/);
  assert.match(experience, /Up to date/);
  assert.match(experience, /Update pending/);
});

test("documents the public unauthenticated deployment", async () => {
  const readme = await readFile(new URL("README.md", root), "utf8");

  assert.match(readme, /https:\/\/golden-gate-flight\.chunhualiao\.workers\.dev/);
  assert.doesNotMatch(readme, /golden-gate-flight-sf\.chunhualiao\.chatgpt\.site/);
});
